### ISSUE TITLE
Add Styletron

### ISSUE THREAD

**Issue by impressivewebs** [DSchau/css-in-js-playground#113]
I believe [Styletron](http://styletron.js.org/) would qualify for inclusion in this playground, correct?

**Comment by DSchau** [comment]
I would love it (and PRs welcome :)).

I know I tried in the past, and ran into some issues, but could've just been doing things foolishly. In general, anything that doesn't require a babel plugin for functionality should work just fine!

**Comment by DSchau** [comment]
Just kidding, I got it :) Main thing I wasn't doing was using the StyletronProvider. Woo hoo!

Will push up a branch and get to it later tonight. I'll close this when done :)

**Comment by impressivewebs** [comment]
Nice, that was fast!

I usually come across other libraries like this when researching stuff for [my newsletter](https://webtoolsweekly.com/) so I'll let you know if there are any others that can be added. I'm pretty sure I've featured others in past issues, but I can't remember them specifically.

**Comment by DSchau** [comment]
Awesome yeah, please let me know!

I try to keep pretty current in this space, but anyone can miss something!
