### ISSUE TITLE
No matching version found for @types/react-dom@next

### ISSUE THREAD

**Issue by kof** [DSchau/css-in-js-playground#18]
Just got this error during installation

➜  css-in-js-playground git:(jss) npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/react-dom@next
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'css-in-js-playground'
npm ERR! notarget

**Comment by kof** [comment]
must be something with my npm and/or dns.

**Comment by kof** [comment]
Ok, I figured the problem, @next version for packages like `@types/react` doesn't exist, there is @latest

**Comment by kof** [comment]
I don't know how you installed that, probably you are using yarn and I was trying to install with npm

**Comment by DSchau** [comment]
@kof good call. I do use yarn! I can fix this later!
