### ISSUE TITLE
add google analytics (or any analytics)

### ISSUE THREAD

**Issue by DSchau** [DSchau/css-in-js-playground#61]
Google Analytics would be a great addition, just so I can track on statistics, users, etc, etc.

API key is `UA-102928446-1`

**Comment by williamparry** [comment]
Hey, are we talking putting it in the index.html or using something like https://github.com/react-ga/react-ga?

**Comment by DSchau** [comment]
@williamparry great question! Performance is always a concern for me, so I'd want a solution that is the most performant and maintainable, if possible!

I think the react-ga solution might be a bit heavy, the script tag approach (with async/defer) might be the way to go. That said, I won't be prescriptive here, so open to any and all solutions.

**Comment by bossbossk20** [comment]
I did it :grin:
