### ISSUE TITLE
Text in the menu is hard to see

### ISSUE THREAD

**Issue by Enchufadoo** [DSchau/css-in-js-playground#98]
Just a suggestion

![image](https://user-images.githubusercontent.com/1263356/32401488-205c8aba-c0ee-11e7-9e22-0d12b56aeb85.png)

**Comment by DSchau** [comment]
Whoa weird! What browser and OS? I tested in Safari, Chrome, and Firefox on MacOS

**Comment by DSchau** [comment]
And thanks for the report!

**Comment by Enchufadoo** [comment]
Oh nevermind... it's only on regular Firefox, I must have some extension messing things because it works great on nightly and Chrome too. Sorry!

**Comment by DSchau** [comment]
Definitely don't be sorry, I appreciate the feedback!

Were you by chance at Thunderplains today?

**Comment by Enchufadoo** [comment]
Nope, I just saw your reddit post.

**Comment by DSchau** [comment]
Oh neat; alright gonna close this, but let me know if you have any other feedback!
